"""A dependency-free, evidence-preserving human-readable project map."""
from __future__ import annotations

import json

from .intelligence import ProjectMap


def render_html(project: ProjectMap) -> str:
    """Render real Graph data as a labelled flow diagram, not a node cloud."""
    data = json.dumps(project.to_dict()).replace("</", "<\\/")
    return _TEMPLATE.replace("__DATA__", data).replace("__NODE_COUNT__", str(len(project.nodes)))


_TEMPLATE = r'''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ImpactPilot Project Intelligence</title>
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;font:14px system-ui,Segoe UI,sans-serif;background:#0b1220;color:#e7eef8;display:grid;grid-template-columns:minmax(640px,1fr) 360px;min-height:100vh}main{padding:24px;overflow:auto}aside{background:#111c2d;padding:20px;overflow:auto;border-left:1px solid #26374e}h1{margin:0 0 4px;font-size:26px}h2{margin-top:0}h3{margin:20px 0 8px;font-size:14px;color:#9fc7f4}.subtle,small{color:#aab9cc}.warning{color:#ffd480;margin:12px 0}.toolbar{display:flex;gap:8px;margin:16px 0;flex-wrap:wrap}input,button{background:#17263a;color:#e7eef8;border:1px solid #405876;padding:9px 11px;border-radius:6px}input{min-width:260px}button{cursor:pointer}button:hover{background:#234061}.legend{display:flex;gap:14px;flex-wrap:wrap;margin:8px 0 14px;color:#b8c7d9}.dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px}.confirmed{background:#59d18c}.heuristic{background:#ffd166}.incomplete{background:#ff7b7b}.unknown{background:#a4b0c0}svg{width:100%;min-width:700px;height:660px;background:linear-gradient(135deg,#0e1928,#111f32);border:1px solid #263d59;border-radius:10px}.edge{stroke:#829ab8;stroke-width:2;fill:none;cursor:pointer}.edge.heuristic{stroke:#ffd166;stroke-dasharray:7 5}.edge.incomplete{stroke:#ff7b7b;stroke-dasharray:3 5}.edge-label{fill:#b9c9da;font-size:11px;cursor:pointer}.node{cursor:pointer}.node rect{fill:#183450;stroke:#63ace8;stroke-width:1.5}.node:hover rect,.node.focus rect{fill:#24527c;stroke:#b7e2ff;stroke-width:2.5}.node-title{fill:white;font-weight:650;font-size:14px}.node-meta{fill:#bdd0e5;font-size:11px}pre{white-space:pre-wrap;word-break:break-word;background:#0b1421;border:1px solid #26374e;padding:10px;border-radius:6px;font-size:12px}.tag{display:inline-block;padding:3px 6px;margin:2px;border-radius:4px;background:#203650;color:#d5e8fa;font-size:11px}
</style>
<main><h1>Project Intelligence</h1><div id="summary" class="subtle"></div><div id="coverage" class="warning"></div><div class="toolbar"><input id="search" placeholder="Filter modules by name"><button onclick="resetMap()">Reset map</button><button onclick="focusSelected()">Focus selected</button></div><div class="legend"><span><i class="dot confirmed"></i>Confirmed evidence</span><span><i class="dot heuristic"></i>Heuristic (dashed)</span><span><i class="dot incomplete"></i>Incomplete (dashed)</span><span>Arrows show Graph-derived direction</span></div><svg id="map" viewBox="0 0 1100 660" role="img" aria-label="Graph-derived project flow diagram"></svg><p class="subtle">Start with one module. Click its card to see files and symbols. Click an arrow label to see the exact relationship evidence. Initial view is bounded to __NODE_COUNT__ modules.</p></main><aside id="detail"><h2>How to read this map</h2><p>Each card is a repository module. An arrow means Entire Graph found one or more relationships from the source module to the destination module.</p><p>Dashed yellow or red arrows are not promises: inspect their evidence and verify critical behavior against source and tests.</p></aside>
<script>
const D=__DATA__,svg=document.querySelector('#map'),detail=document.querySelector('#detail');let selected=null;const esc=x=>String(x??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const trustClass=e=>e.trust.incomplete?'incomplete':e.trust.heuristic?'heuristic':'';
function layout(nodes){const p={};nodes.forEach((n,i)=>p[n.id]=[150+(i%4)*240,105+Math.floor(i/4)*145]);return p}function lineEnd(a,b){const dx=b[0]-a[0],dy=b[1]-a[1],d=Math.max(1,Math.hypot(dx,dy));return[[a[0]+dx*76/d,a[1]+dy*34/d],[b[0]-dx*76/d,b[1]-dy*34/d]]}
function render(filter=''){const nodes=D.nodes.filter(n=>!filter||n.label.toLowerCase().includes(filter)),pos=layout(nodes);let html='<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#829ab8"/></marker></defs>';D.edges.filter(e=>pos[e.source]&&pos[e.target]).forEach(e=>{const[a,b]=lineEnd(pos[e.source],pos[e.target]),mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2,kind=trustClass(e),label=`${e.types.join(', ')} · ${e.count}`;html+=`<g onclick="showEdge('${e.id}')"><path class="edge ${kind}" marker-end="url(#arrow)" d="M${a[0]},${a[1]} L${b[0]},${b[1]}"/><text class="edge-label" x="${mx}" y="${my-5}" text-anchor="middle">${esc(label)}</text></g>`});nodes.forEach(n=>{const[x,y]=pos[n.id],on=selected===n.id?'focus':'';html+=`<g class="node ${on}" onclick="showNode('${n.id}')"><rect x="${x-82}" y="${y-34}" width="164" height="68" rx="9"/><text class="node-title" x="${x}" y="${y-7}" text-anchor="middle">${esc(n.label)}</text><text class="node-meta" x="${x}" y="${y+14}" text-anchor="middle">${n.files.length} files · ${n.incoming+n.outgoing} links</text></g>`});svg.innerHTML=html}
function showNode(id){selected=id;const n=D.nodes.find(x=>x.id===id),edges=D.edges.filter(e=>e.source===id||e.target===id),near=new Set([id]);edges.forEach(e=>{near.add(e.source);near.add(e.target)});const files=D.nodes.filter(x=>near.has(x.id)).flatMap(x=>x.files).slice(0,20);detail.innerHTML=`<h2>${esc(n.label)}</h2><p><b>Module flow</b><br>Incoming: ${n.incoming} · Outgoing: ${n.outgoing}<br>${n.files.length} files · ${n.symbols.length} symbols</p><h3>Trust summary</h3>${Object.entries(n.trust).map(([k,v])=>`<span class="tag">${esc(k)}: ${v}</span>`).join('')||'<p class="subtle">No inter-module evidence.</p>'}<h3>Start here</h3><p>${n.files.slice(0,8).map(esc).join('<br>')||'No files reported.'}</p><h3>Important symbols</h3><p>${n.symbols.slice(0,12).map(s=>`${esc(s.name)} <small>${esc(s.file_path)}:${esc(s.start_line)}</small>`).join('<br>')||'No symbols reported.'}</p><h3>Follow the arrows</h3>${edges.map(e=>`<button onclick="showEdge('${e.id}')">${esc(e.types.join(', '))} → ${e.count} relationship(s)</button>`).join(' ')||'<p class="subtle">No visible inter-module edges.</p>'}<h3>AI Context</h3><pre>${esc(JSON.stringify({target:n.label,relevant_files:files,coverage:D.coverage},null,2))}</pre>`;render(document.querySelector('#search').value.toLowerCase())}
function showEdge(id){const e=D.edges.find(x=>x.id===id),source=D.nodes.find(n=>n.id===e.source),target=D.nodes.find(n=>n.id===e.target);detail.innerHTML=`<h2>${esc(source?.label)} → ${esc(target?.label)}</h2><p><b>${esc(e.types.join(', '))}</b><br>${e.count} underlying Graph relationship(s)</p><h3>Trust</h3>${Object.entries(e.trust).map(([k,v])=>`<span class="tag">${esc(k)}: ${v}</span>`).join('')}<h3>Relationship evidence: why this arrow exists</h3><pre>${esc(JSON.stringify(e.evidence,null,2))}</pre><p class="warning">If this edge is heuristic, incomplete, or unknown, inspect the cited source and run a targeted test before relying on it.</p>`}
function resetMap(){selected=null;document.querySelector('#search').value='';detail.innerHTML='<h2>How to read this map</h2><p>Click a module card, then follow its labelled arrows.</p>';render()}function focusSelected(){if(!selected){detail.innerHTML='<h2>Choose a module first</h2><p>Click a card, then use Focus selected to filter the map around it.</p>';return}const n=D.nodes.find(x=>x.id===selected);document.querySelector('#search').value=n.label;render(n.label.toLowerCase())}document.querySelector('#search').oninput=e=>render(e.target.value.toLowerCase());document.querySelector('#summary').textContent=`${D.total_files} files · ${D.total_symbols} symbols · ${D.total_relations} relationships · ${D.nodes.length} visible modules`;document.querySelector('#coverage').textContent=D.coverage==='complete'?'Graph coverage: complete structural analysis reported.':`Graph coverage: ${D.coverage}. Some relationships may be missing; verify critical paths.`;render();
</script>'''
