"""Small self-contained interactive renderer; no framework or fake data."""
from __future__ import annotations
import json
from .intelligence import ProjectMap


def render_html(project: ProjectMap) -> str:
    data = json.dumps(project.to_dict()).replace("</", "<\\/")
    return f'''<!doctype html><meta charset="utf-8"><title>ImpactPilot Project Intelligence</title>
<style>body{{margin:0;font:14px system-ui;background:#10151f;color:#e8edf5;display:grid;grid-template-columns:1fr 330px;height:100vh}}main{{padding:22px;overflow:auto}}aside{{background:#18212e;padding:20px;overflow:auto;border-left:1px solid #334155}}input,button{{background:#202d3d;color:#e8edf5;border:1px solid #536273;padding:8px;border-radius:5px}}svg{{width:100%;height:600px;background:#131c28;border-radius:8px}}.node{{cursor:pointer}}.node rect{{fill:#26384e;stroke:#6aa6d9;stroke-width:1.5}}.node:hover rect,.selected rect{{fill:#315276}}line{{stroke:#8ba4bf;stroke-width:1.5}}.heuristic{{stroke-dasharray:6}}small{{color:#b9c4d2}}</style>
<main><h1>Project Intelligence</h1><p id="summary"></p><input id="search" placeholder="Search symbols or files"><button onclick="reset()">Reset</button><svg id="map" viewBox="0 0 1000 600"></svg><p><small>Initial view is bounded to {len(project.nodes)} modules. Click a module to inspect its Graph-derived files, symbols, relationships, trust, and AI context.</small></p></main><aside id="detail"><h2>Evidence-first map</h2><p>Select a module or relationship. Graph uncertainty is never shown as certainty.</p></aside>
<script>const D={data}, svg=document.querySelector('#map'), detail=document.querySelector('#detail');
function esc(x){{return String(x??'').replace(/[&<>]/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;'}}[c]))}};
function render(filter=''){{svg.innerHTML='';let n=D.nodes.filter(x=>!filter||x.label.toLowerCase().includes(filter));let pos={{}};n.forEach((x,i)=>pos[x.id]=[130+(i%4)*240,100+Math.floor(i/4)*180]);D.edges.filter(e=>pos[e.source]&&pos[e.target]).forEach(e=>{{let a=pos[e.source],b=pos[e.target],h=e.trust.heuristic?'heuristic':'';svg.innerHTML+=`<line class="${{h}}" x1="${{a[0]}}" y1="${{a[1]}}" x2="${{b[0]}}" y2="${{b[1]}}"></line>`}});n.forEach(x=>{{let [a,b]=pos[x.id];svg.innerHTML+=`<g class="node" data-id="${{x.id}}"><rect x="${{a-90}}" y="${{b-40}}" width="180" height="80" rx="8"/><text x="${{a}}" y="${{b-5}}" text-anchor="middle" fill="white">${{esc(x.label)}}</text><text x="${{a}}" y="${{b+18}}" text-anchor="middle" fill="#b9c4d2">${{x.files.length}} files · ${{x.incoming+x.outgoing}} links</text></g>`}});document.querySelectorAll('.node').forEach(el=>el.onclick=()=>show(el.dataset.id));}}
function show(id){{let n=D.nodes.find(x=>x.id===id), es=D.edges.filter(e=>e.source===id||e.target===id); detail.innerHTML=`<h2>${{esc(n.label)}}</h2><p><b>Module</b><br>${{n.files.length}} files, ${{n.symbols.length}} symbols<br>Incoming: ${{n.incoming}} · Outgoing: ${{n.outgoing}}</p><h3>Trust</h3><pre>${{esc(JSON.stringify(n.trust,null,2))}}</pre><h3>Files</h3><p>${{n.files.map(esc).join('<br>')}}</p><h3>Symbols</h3><p>${{n.symbols.slice(0,20).map(s=>esc(s.name)+' <small>'+esc(s.file_path)+':'+esc(s.start_line)+'</small>').join('<br>')}}</p><h3>Relationships / evidence</h3>${{es.map(e=>`<button onclick="edge('${{e.id}}')">${{esc(e.types.join(', '))}} (${{e.count}})</button>`).join(' ')}}<h3>AI Context</h3><pre>${{esc(JSON.stringify(context(id),null,2))}}</pre>`;}}
function edge(id){{let e=D.edges.find(x=>x.id===id);detail.innerHTML='<h2>Relationship evidence</h2><pre>'+esc(JSON.stringify(e,null,2))+'</pre><p>Heuristic, incomplete, or unknown evidence requires source inspection and targeted tests.</p>'}}
function context(id){{let n=D.nodes.find(x=>x.id===id), ids=new Set([id]);D.edges.forEach(e=>{{if(e.source===id)ids.add(e.target);if(e.target===id)ids.add(e.source)}});let files=D.nodes.filter(n=>ids.has(n.id)).flatMap(n=>n.files);return {{target:n.label,relevant_files:files.slice(0,20),excluded_file_count:Math.max(0,D.total_files-files.length),coverage:D.coverage}}}}
function reset(){{document.querySelector('#search').value='';render()}}document.querySelector('#search').oninput=e=>render(e.target.value.toLowerCase());document.querySelector('#summary').textContent=`${{D.total_files}} files · ${{D.total_symbols}} symbols · ${{D.total_relations}} relationships · Graph coverage: ${{D.coverage}}`;render();</script>'''
